// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cryptfest.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Entities.UserEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserLogInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientRequestId");

                    b.HasIndex("UserLogInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Data.Entities.UserEntities.UserLogInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLogInfo");
                });

            modelBuilder.Entity("API.Data.Entities.Wallet.CryptoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId");

                    b.ToTable("CryptoAsset");
                });

            modelBuilder.Entity("API.Data.Entities.Wallet.CryptoTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromAssetId")
                        .HasColumnType("int");

                    b.Property<int?>("ToAssetId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromAssetId");

                    b.HasIndex("ToAssetId");

                    b.HasIndex("WalletId");

                    b.ToTable("CryptoExchanges");
                });

            modelBuilder.Entity("API.Data.Entities.WalletEntities.CryptoAssetMarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PercentChange1h")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PercentChange24h")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PercentChange30d")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PercentChange60d")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PercentChange7d")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.ToTable("CryptoAssetMarketData");
                });

            modelBuilder.Entity("API.Data.Entities.WalletEntities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatisticId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatisticId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Cryptfest.Data.Entities.ClientRequest.ClientRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClientRequests");
                });

            modelBuilder.Entity("Cryptfest.Data.Entities.WalletEntities.CryptoBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("Usdt")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("WalletId");

                    b.ToTable("CryptoBalances");
                });

            modelBuilder.Entity("Cryptfest.Data.Entities.WalletEntities.WalletStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Apy")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("TotalDeposit")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.ToTable("WalletStatistics");
                });

            modelBuilder.Entity("API.Data.Entities.UserEntities.User", b =>
                {
                    b.HasOne("Cryptfest.Data.Entities.ClientRequest.ClientRequest", "ClientRequest")
                        .WithMany()
                        .HasForeignKey("ClientRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.UserEntities.UserLogInfo", "UserLogInfo")
                        .WithMany()
                        .HasForeignKey("UserLogInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientRequest");

                    b.Navigation("UserLogInfo");
                });

            modelBuilder.Entity("API.Data.Entities.Wallet.CryptoAsset", b =>
                {
                    b.HasOne("API.Data.Entities.WalletEntities.CryptoAssetMarketData", "MarketData")
                        .WithMany()
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketData");
                });

            modelBuilder.Entity("API.Data.Entities.Wallet.CryptoTransaction", b =>
                {
                    b.HasOne("API.Data.Entities.Wallet.CryptoAsset", "FromAsset")
                        .WithMany()
                        .HasForeignKey("FromAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Data.Entities.Wallet.CryptoAsset", "ToAsset")
                        .WithMany()
                        .HasForeignKey("ToAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Data.Entities.WalletEntities.Wallet", null)
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId");

                    b.Navigation("FromAsset");

                    b.Navigation("ToAsset");
                });

            modelBuilder.Entity("API.Data.Entities.WalletEntities.Wallet", b =>
                {
                    b.HasOne("Cryptfest.Data.Entities.WalletEntities.WalletStatistic", "Statistic")
                        .WithMany()
                        .HasForeignKey("StatisticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.UserEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Statistic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cryptfest.Data.Entities.WalletEntities.CryptoBalance", b =>
                {
                    b.HasOne("API.Data.Entities.Wallet.CryptoAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.WalletEntities.Wallet", "Wallet")
                        .WithMany("Balances")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("API.Data.Entities.WalletEntities.Wallet", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
